#ifndef __GITHUB_MYUN2__RUBYEXT_H__
#define __GITHUB_MYUN2__RUBYEXT_H__

#include "ruby.h"

#define RB_MODULE	VALUE
#define RB_CLASS	VALUE

#define RB_CLASS_OBJECT		rb_cObject

#define RB_DECLARE_METHOD(C, NAME, FUNC, PARAMS)	rb_define_method(C, NAME, FUNC, PARAMS);
#define RB_DECLARE_METHOD_0(C, NAME, FUNC)			RB_DECLARE_METHOD(C, NAME, FUNC, 0)
#define RB_DECLARE_METHOD_1(C, NAME, FUNC)			RB_DECLARE_METHOD(C, NAME, FUNC, 1)
#define RB_DECLARE_METHOD_2(C, NAME, FUNC)			RB_DECLARE_METHOD(C, NAME, FUNC, 2)

#define RB_STR(S)			rb_str_new2(S)

#endif//__GITHUB_MYUN2__RUBYEXT_H__
